name: Deploy to TestFlight

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up SSH for accessing the private match repository
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Set up secrets
        run:  echo "BASE_URL = ${{ secrets.BASE_URL }}" > "NUK Unofficial APP/App/Configuration/Secrets.xcconfig"
      - name: Run tests via fastlane
        env:
            APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
            APPLE_ID: ${{ secrets.APPLE_ID }}
            ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
            TEAM_ID: ${{ secrets.TEAM_ID }}
            APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
            APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
            APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
            APP_STORE_CONNECT_API_KEY_IS_KEY_CONTENT_BASE64: ${{ secrets.APP_STORE_CONNECT_API_KEY_IS_KEY_CONTENT_BASE64 }}
            MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: fastlane tests
      - name: Deploy to TestFlight via fastlane
        env:
            APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
            APPLE_ID: ${{ secrets.APPLE_ID }}
            ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
            TEAM_ID: ${{ secrets.TEAM_ID }}
            APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
            APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
            APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
            APP_STORE_CONNECT_API_KEY_IS_KEY_CONTENT_BASE64: ${{ secrets.APP_STORE_CONNECT_API_KEY_IS_KEY_CONTENT_BASE64 }}
            MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: fastlane beta
